#!/usr/bin/env bash

which java > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Java is not installed"
    echo "Use 'sudo apt-get install openjdk' to install java"
    exit 1
fi

export CLASSPATH=".:antlr-4.11.1-complete.jar:$CLASSPATH"
java -jar antlr-4.11.1-complete.jar Python3Lexer.g4
java -jar antlr-4.11.1-complete.jar Python3Parser.g4
javac *.java
java org.antlr.v4.gui.TestRig Python3 file_input -ps python3.ps
rm *.class Python3ParserListener.java Python3ParserBaseListener.java Python3Parser.tokens Python3Parser.java Python3Parser.interp Python3Lexer.tokens Python3Lexer.java Python3Lexer.interp

